builds:
- goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    amd64: 64-bit
