name: Release

on:
  push:
    branches:
    - "!*"
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Publish Docker image to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: ${{ github.repository }}/cli
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_names: true
