name: release

on:
  push:
    branches:
    - "!*"
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: unshallow
      run: git fetch --prune --unshallow
    - name: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: releaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
